### Create a Plumbing service
POST http://localhost:3000/v1/service_categories
Content-Type: application/json

{
  "name": "Plumbing",
  "description": "Fix leaks and pipes",
  "basePrice": 500,
  "estimatedDurationMinutes": 60
}

### Create a Cleaning service
POST http://localhost:3000/v1/service_categories
Content-Type: application/json

{
  "name": "Cleaning",
  "description": "House cleaning service",
  "basePrice": 800,
  "estimatedDurationMinutes": 120
}




### Create a Booking
POST http://localhost:3000/v1/bookings
Content-Type: application/json

{
  "customerId": 1,
  "serviceCategoryId": 1,
  "scheduledAt": "2026-08-13T17:00:00",
  "estimatedPrice": 0
}

### create offer
POST http://localhost:3000/v1/allocation/bookings/1/offer
Content-Type: application/json

{
  "workerId": 10,
  "tier": "tier1",
  "ttlSeconds": 5
}
###
POST http://localhost:3000/v1/allocation/bookings/1/accept
Content-Type: application/json

{
  "workerId": 10
}

###
POST http://localhost:3000/v1/allocation/bookings/1/offer
Content-Type: application/json

{
  "workerId": 20,
  "tier": "tier2",
  "ttlSeconds": 5
}

###
POST http://localhost:3000/v1/allocation/bookings/1/accept
Content-Type: application/json
{
  "workerId": 2
}

### Worker 1
POST http://localhost:3000/v1/allocation/bookings/1/offer
Content-Type: application/json

{
  "workerId": 1,
  "tier": "TIER1",
  "ttlSeconds": 30
}

### Worker 2
POST http://localhost:3000/v1/allocation/bookings/1/offer
Content-Type: application/json

{
  "workerId": 2,
  "tier": "TIER1",
  "ttlSeconds": 5
}

### Worker 3
POST http://localhost:3000/v1/allocation/bookings/1/offer
Content-Type: application/json

{
  "workerId": 3,
  "tier": "TIER1",
  "ttlSeconds": 5
}


### Worker 2 accepts the offer
POST http://localhost:3000/v1/allocation/bookings/1/accept
Content-Type: application/json

{
  "workerId": 2
}

### Worker 1 accepts the offer
POST http://localhost:3000/v1/allocation/bookings/1/accept
Content-Type: application/json

{
  "workerId": 1
}





### Worker A accepts the offer
POST http://localhost:3000/v1/allocation/bookings/1/accept
Content-Type: application/json

{
  "workerId": "A"
}
